Scruffy Grape Koala

Low/Info

# [med] [transfer] function can fail without exception

## Summary
'transfer' function can fail without exception

## Vulnerability Detail
Considering that an exception occurs in the `transfer` function, error handling is performed using a try catch statement.
However, exception does not always occur when the transfer function fails. 
Since it may fail without an error, I think it would be better to write it explicitly.

## Impact
When transfer fails, you can catch all parts where the event is not emitted.

## Code Snippet
https://github.com/sherlock-audit/2024-06-leveraged-vaults/blob/main/leveraged-vaults-private/contracts/vaults/common/VaultRewarderLib.sol#L316


[Before]
```solidity
            try IEIP20NonStandard(rewardToken).transfer(account, rewardToClaim) {
                bool success = TokenUtils.checkReturnCode();
                if (success) {
                    emit VaultRewardTransfer(rewardToken, account, rewardToClaim);
                } else {
                    emit VaultRewardTransfer(rewardToken, account, 0);
                }
            // Emits zero tokens transferred if the transfer fails.
            } catch {
                emit VaultRewardTransfer(rewardToken, account, 0);
            }
```

## Tool used
VS Code

Manual Review

## Recommendation
I recommended the following code.
[After]
```solidity
bool successTransfer = IEIP20NonStandard(rewardToken).transfer(account, rewardToClaim);
if (successTransfer) {
  //... ...
} else {
  emit VaultRewardTransfer(rewardToken, account, 0);
}
```
